### ISSUE TITLE
Improved OS abstraction

### ISSUE THREAD

**Issue by tcheko** [lexborisov/Modest#10]
Hi Lexbor, 

It would be nice if all the OS abstraction was made with split files per operating system instead of relying on #ifdef statements which can be cumbersome to maintain or expand. 

os/windows
os/linux
os/macos
os/bsd
os/pickyourpoison

I see four obvious abstraction targets : memory, threading, io, and timer.

**Comment by lexborisov** [comment]
Added in [split](https://github.com/lexborisov/Modest/tree/split) branch 
Soon branch Split will be merged to master

**Comment by lexborisov** [comment]
Done!
