### ISSUE TITLE
name of shared libraries

### ISSUE THREAD

**Issue by vtorri** [lexborisov/Modest#16]
if version is VMAJ.VMIN.VMIC : 
on Windows: libmodest-$(VMAJ).dll and libmodest.dll.a for import library
on UNIX: libmodest-$(VMAJ).$(VMIN).$(VMIC).so and libmodest.a for static one

on Unix, there are also symbolic links to libmodest-$(VMAJ).$(VMIN).so and libmodest-$(VMAJ).so

**Comment by lexborisov** [comment]
Changes 
Thanks!
