### ISSUE TITLE
При сериализации border/padding не пишет значение

### ISSUE THREAD

**Issue by Azq2** [lexborisov/Modest#2]
```
    Node: <img style="border:0px" src="ololo" alt>
    Declaration: border: ;
```

Здесь вообще пропустило border почему-то:

```
    Node: <img style="border: 1px; padding: 1px; padding: 1%;" src="ololo" alt>
    Declaration: padding: 1px; padding: ;
```

Я для тестов использовал код из examples/declarations/style_attr_low_level.c

Или это ещё не доработано и нормально?

**Comment by lexborisov** [comment]
border по планам завтра (там почти всё уже есть, border-style, border-width, border-color...), а с padding разберусь, должен был отработать. Список обрабатываемых свойств можно посмотреть [тут](https://github.com/lexborisov/Modest/blob/master/source/mycss/property/parser.c).

Вот написанием тестов бы кто занялся для каждого свойства...

P.S.: вообще, конечно, лучше писать всё по английски, смотрители часто уходят если много начинается не английской письменности, ну и просто им не понятно, что происходит, может какой мега-критичный баг обнаружили, а всё на русском :). Но если с английским проблемы, то можно на почту или уж так как есть.

**Comment by Azq2** [comment]
Ок, понял)

**Comment by lexborisov** [comment]
Added and fixed!
Thanks!
