### ISSUE TITLE
have a debug and release mode

### ISSUE THREAD

**Issue by vtorri** [lexborisov/Modest#21]
in debug mode, these flags should be passed to the compiler : -g3 -ggdb3 -O0 -fno-omit-frame-pointer (to allow good stack unwiding for gdb or other debugguers)

in release mode, at least -fomit-frame-pointer

**Comment by lexborisov** [comment]
Done!
make MyCORE_BUILD_DEBUG=YES
it added "-g3 -ggdb3 -O0 -fno-omit-frame-pointer"
