### ISSUE TITLE
missing api method for css_entry->selectors

### ISSUE THREAD

**Issue by kostya** [lexborisov/Modest#3]
https://github.com/lexborisov/Modest/blob/master/examples/selectors/selectors_low_level.c#L83

also `mycss_selectors_list_t *list`, not free in example, is there any method for this?

**Comment by lexborisov** [comment]
Added to [example](https://github.com/lexborisov/Modest/blob/master/examples/selectors/selectors_low_level.c#L104)

See [in header](https://github.com/lexborisov/Modest/blob/master/source/mycss/selectors/list.h#L53)

Thanks!

**Comment by kostya** [comment]
thanks, but what about `api method for css_entry->selectors`?

**Comment by lexborisov** [comment]
Done!
