### ISSUE TITLE
MODEST_PORT_NAME not used in source code

### ISSUE THREAD

**Issue by vtorri** [lexborisov/Modest#31]
Hello

MODEST_PORT_NAME is passed to the preprocessor : in Makefile:

MODEST_CFLAGS += -DMODEST_PORT_NAME=$(MODEST_PORT_NAME)

but this macro is not used in any source file. Is it really useful to pass it to the preprocessor ?

**Comment by lexborisov** [comment]
Hi!
Need to remove this. Remnant of the past

**Comment by vtorri** [comment]
looking at lexbor only now, so closing
