### ISSUE TITLE
Python bindings clarification

### ISSUE THREAD

**Issue by ducdetronquito** [lexborisov/Modest#35]
Hi !

I've just seen the link to the Python binding you added ! (Kudos to @rushter by the way)
Would you mind to specify that this is a Cython binding, and not exactly python ?

**Comment by rushter** [comment]
Why it's not exactly Python? Cython is just additional dependency which compiles special syntaxis down to C code with Python API calls. 
Thus, it's just a Python package with binary modules.

For example, take a look at lxml, scipy, pandas, scikit-learn. They all using Cython and you will not notice that unless you need to dig in the source code. 

Don't confuse people with that. There is nothing special about it, you just install it via pip and ready to use in Python.

**Comment by ducdetronquito** [comment]
Hi @rushter ,

Fine, but is there a way to enforce Cython as a dependencies ? Because, when I `pip3 install selectolax` it raises an exception as I have not Cython installed.

Here is the trace:

```bash
Collecting selectolax
  Using cached selectolax-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pxywyvzd/selectolax/setup.py", line 8, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pxywyvzd/selectolax/

As it is not directly related to Modest, I can submit a issue on your repository if you like.

```

**Comment by rushter** [comment]
@ducdetronquito I will fix it. That's because `lxml` uses pretranspiled source code if you don't have Cython.
