### ISSUE TITLE
Add CSS selector for ":contains(text)"

### ISSUE THREAD

**Issue by f34nk** [lexborisov/Modest#36]
Hello,
I would like to implement a new selector for the pseudo class `:contains(text)`.

>:contains() Selector
>Select all elements that contain the specified text. 

The current W3C CSS specification [left this section intentionally blank](https://www.w3.org/TR/selectors-3/#content-selectors). However, some information can be found [in an old spec from 2001](https://www.w3.org/TR/2001/CR-css3-selectors-20011113/#content-selectors).

Since I am new to the code-stack would you be so kind and give me some hints? 
I will document my progress here.

Best, Fr34nk

**Comment by f34nk** [comment]
I followed the implementation of the `:has()` pseudo class.

You can [compare my changes here](https://github.com/lexborisov/Modest/compare/master...f34nk:support-for-pseudo-class-contains) (I am sorry, my plugin removed all the trailing spaces).

I added all the necessary functions, enums and incremented [MyCSS_SELECTORS_SUB_TYPE_PSEUDO_CLASS_FUNCTION_LAST_ENTRY](https://github.com/lexborisov/Modest/compare/master...f34nk:support-for-pseudo-class-contains#diff-cd37217452bb9e8ff747ad2b434b19afR116).

However, running `make` I get the following **error**.

```
cc -Wall -Werror -pipe -pedantic -Isource -fPIC -D_POSIX_C_SOURCE=199309L -O2 -Wno-unused-variable -Wno-unused-function -std=c99 -DMODEST_BUILD_OS=Linux -DMODEST_PORT_NAME=posix -DMyCORE_OS_LINUX   -c -o source/modest/finder/finder.o source/modest/finder/finder.c
In file included from source/modest/finder/finder.c:22:0:
source/modest/finder/resource.h:57:5: error: ‘modest_finder_selector_sub_type_pseudo_class_function_contains’ undeclared here (not in a function)
     modest_finder_selector_sub_type_pseudo_class_function_contains             /* MyCSS_SELECTORS_SUB_TYPE_PSEUDO_CLASS_FUNCTION_CONTAINS */
     ^
make: *** [source/modest/finder/finder.o] Error 1
```

I don't quite understand what I did wrong since this error points to the `modest_finder_static_selector_sub_type_pseudo_class_function_map` and I thought the "xy_LAST_ENTRY" holds the correct value?

Any help greatly appreciated.

**Comment by lexborisov** [comment]
Hi!
I will try to help with this, at the moment there is not much time. Later I'll figure it out.

**Comment by f34nk** [comment]
Ok, I found it. Of course I missed something :)

**Comment by f34nk** [comment]
Hey man. I am close to refactoring my Elixir binding package [modest_ex](https://github.com/f34nk/modest_ex) and the first major release.
However, it would be awesome if I would be able to include the ":contains" selector in my Modest fork. 

As far as I can see I added all functions and some **dummy code** for the selector. It compiles but the test returns with "BAD_SELECTOR".
You can [compare my changes here](https://github.com/lexborisov/Modest/compare/master...f34nk:support-for-pseudo-class-contains).

Would you be so kind and take a look where I went wrong?

For example, what does [function_resource.h](https://github.com/lexborisov/Modest/compare/master...f34nk:support-for-pseudo-class-contains#diff-586f71b5dd4e42b8b79fb40653da4325R86) do?

Best, f34nk

**Comment by f34nk** [comment]
So, [here is the Problem](https://github.com/lexborisov/Modest/blob/master/source/mycss/selectors/parser.c#L274):
`mycss_selectors_function_begin_f to_func = mycss_function_begin_by_name(str->data, str->length);` in `parser.c` does not return the correct function for "contains".

**Comment by lexborisov** [comment]
@f34nk 
You need to generate new `mycss_selectors_function_begin_map_index` variable  in [function_resource.h](https://github.com/f34nk/Modest/blob/master/source/mycss/selectors/function_resource.h) file.

For generate new variable resource use [utils/MyCSS/functions.pl](https://github.com/f34nk/Modest/blob/support-for-pseudo-class-contains/utils/MyCSS/functions.pl) file. Append your function name to `my $func_map = {...}` hash and try to run script.

See `mycss_selectors_sub_type_pseudo_class_function` in [myosi.h](https://github.com/f34nk/Modest/blob/master/source/mycss/selectors/myosi.h), append your function name like a
```C
    ...
    MyCSS_SELECTORS_SUB_TYPE_PSEUDO_CLASS_FUNCTION_CONTAINS           = 0x0f,
    MyCSS_SELECTORS_SUB_TYPE_PSEUDO_CLASS_FUNCTION_LAST_ENTRY       = 0x10
    ...
```
and append your function to `mycss_selectors_value_function_destroy_map` in
[value_resource.h](https://github.com/f34nk/Modest/blob/master/source/mycss/selectors/value_resource.h) file by index `MyCSS_SELECTORS_SUB_TYPE_PSEUDO_CLASS_FUNCTION_CONTAINS`, some like a:
```C
    ...
    mycss_selectors_value_pseudo_class_function_nth_of_type_destroy,
    mycss_selectors_value_pseudo_class_function_nth_of_type_contains
};
```

And append serialization for your function to [serialization.c](https://github.com/f34nk/Modest/blob/master/source/mycss/selectors/serialization.c#L153)
