### ISSUE TITLE
ModestEx - Elixir/Erlang binding to Modest library

### ISSUE THREAD

**Issue by f34nk** [lexborisov/Modest#37]
Hi Alexander,
I just want to announce that I published my first draft of a Elixir/Erlang binding to Modest.

[**ModestEx**](https://github.com/f34nk/modest_ex)

Still under development but the possibilities are very promising.

Best, F34nk

**Comment by lexborisov** [comment]
Hi
Awesome!

Link added to [readme.md](https://github.com/lexborisov/Modest)

**Comment by f34nk** [comment]
My announcement on the [elixirforum](https://elixirforum.com/t/modestex-library-for-parsing-html-with-css-selectors-and-dom-mutation/12793/2) - if you are curious :)
