### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by aajjbb** [lexborisov/Modest#8]
Hi. Trying to build modest's git version right now leads to the following error: 

`modest/css_property_to_node.c: In function ‘main’: `
`modest/css_property_to_node.c:114:21: error: variable ‘status’ set but not used [-Werror=unused-but-set-variable]
     modest_status_t status = modest_init(modest);`

The error came from the build process for the `example` folder. I know that modest sets `-Wno-unused-variable` so I got confused there.

**Comment by lexborisov** [comment]
Hi @aajjbb,
I have this problem arose in ```gcc version 6```. Fixed!

Thanks!
