### ISSUE TITLE
Future of Modest

### ISSUE THREAD

**Issue by baseplate-admin** [lexborisov/Modest#87]
Hi There,
Thanks for creating `Modest` and `lexbor`

It seems that you now have a new project `lexbor` that aims to do what `Modest` is doing. So with that in mind, what's the future of this repository ?

If this repository is deprecated ( since the last commit was almost over 2 years ago ) why not archive this project and point to `lexbor` ?

I originally came from https://github.com/rushter/selectolax/issues/82 .. If we deprecate this repo, we would have a stronger argument to remove `modest` from  `selectolax`

**Comment by lexborisov** [comment]
Hi @baseplate-admin 

I wouldn't want to force anyone to do anything.
But sending this repository to the archive seems like a good idea.

**Comment by baseplate-admin** [comment]
>  But sending this repository to the archive seems like a good idea.

Thanks a bunch for considering my opinion :)
