### ISSUE TITLE
collection bug

### ISSUE THREAD

**Issue by kostya** [lexborisov/Modest#9]
```crystal
    str = "<html>" + "<div class=A>ooo</div>" * 20000 + "</html>"
    parser = Myhtml::Parser.new(str)

    c = 0
    parser.css("div").each do |node|
      c += 1 if node.attribute_by("class") == "A"
    end
    p c
```

output 1566
expected 20000

is this the same bug https://github.com/lexborisov/myhtml/issues/84?

**Comment by lexborisov** [comment]
Fixed!
Thanks!

**Comment by kostya** [comment]
can you also please push release for modest?

**Comment by lexborisov** [comment]
I can not make a release. The project is under development.

**Comment by kostya** [comment]
i mean, just create any tag, `0.0.1.dev` or something, and this appears in releases page. faster to download from it, than from git.
